# Generated by Django 3.2 on 2022-02-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_remittance_teller'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='price_per_litre',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
