# Generated by Django 3.2 on 2022-02-26 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remittance_price_per_litre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remittance',
            name='amount',
        ),
        migrations.AddField(
            model_name='remittance',
            name='no_of_litres',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remittance',
            name='price_per_litre',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
